name: Build and push to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet restore && dotnet publish -o site

      - name: Create zip package
        run: cd site && zip -r ../site.zip *

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@21
        with:
          aws_access_key: ${{AWS_KEY}}
          aws_secret_key: ${{USER_NAME}}
          application_name: skolaAPI
          environment_name: SkolaAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip
